name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<your-ec2-ip-address> << 'EOF'
          cd /home/ec2-user/Discordbot-Makeevskiy-rodnichok
          git pull origin main
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          pip3 install -r requirements.txt
          sudo systemctl restart discordbot.service
          EOF
